name: pip_view
description: Widget to allow the presentation of a widget below a floating one.
version: 1.0.0
homepage: https://github.com/lslv1243/pip_view

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
